app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

places:
    resource: "@AppBundle/Controller/PlaceController.php"
    type:     rest

users:
    resource: "@AppBundle/Controller/UserController.php"
    type:     rest
