app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

places:
    resource: "@AppBundle/Controller/PlaceController.php"
    type:     rest

prices:
    resource: "@AppBundle/Controller/Place/PriceController.php"
    type:     rest

themes:
    resource: "@AppBundle/Controller/Place/ThemeController.php"
    type:     rest

users:
    resource: "@AppBundle/Controller/UserController.php"
    type:     rest

preferences:
    resource: "@AppBundle/Controller/User/PreferenceController.php"
    type:     rest

auth-tokens:
    resource: "@AppBundle/Controller/AuthTokenController.php"
    type:     rest